<a href="https://colab.research.google.com/github/tejas990/abc/blob/main/pre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 


In [3]:
dataset=pd.read_csv('Data.csv')


In [4]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1]
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3]=imputer.fit_transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [18]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1]
[0 1]


In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform
(x_train[:,3:])
x_test[:,3:]=sc.fit_transform
(x_test[:,3:])
print(x_train,x_test)


[[0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound met